allowBuilds:
  '@parcel/watcher': true
  '@posthog/cli': true
  core-js: true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
minimumReleaseAgeExclude:
  - '@nuxt/kit@4.5.1'
  - '@nuxt/nitro-server@4.5.1'
  - '@nuxt/schema@4.5.1'
  - '@nuxt/vite-builder@4.5.1'
  - nuxt@4.5.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - vue-demi
  - workerd
