allowBuilds:
  '@parcel/watcher': true
  '@posthog/cli': true
  core-js: true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - vue-demi
  - workerd
